ADD_LIBRARY(
  APP STATIC EXCLUDE_FROM_ALL
  ${ASSETS} APP.cpp APP.hpp DataContainer.cpp DataContainer.hpp)

ADD_LIBRARY(
  OsAbstraction INTERFACE)

ADD_LIBRARY(
  BSP INTERFACE)

ADD_LIBRARY(
  bootloader INTERFACE)

IF(CMAKE_BUILD_TYPE STREQUAL "x86_Clang" OR CMAKE_BUILD_TYPE STREQUAL "x86_GCC")
  TARGET_LINK_LIBRARIES(OsAbstraction INTERFACE PcOsAbstraction)
  TARGET_LINK_LIBRARIES(BSP INTERFACE PcBSP)
  TARGET_LINK_LIBRARIES(bootloader INTERFACE X86_BootLoader)
ELSE()
  TARGET_LINK_LIBRARIES(OsAbstraction INTERFACE StmOsAbstraction)
  TARGET_LINK_LIBRARIES(BSP INTERFACE StmBSP)
  TARGET_LINK_LIBRARIES(bootloader INTERFACE STM_BootLoader)
ENDIF()

TARGET_LINK_LIBRARIES(
  APP
  PRIVATE OsAbstraction BSP EmbedGUI protobuf_wrapper debug_messages_handler)

TARGET_INCLUDE_DIRECTORIES(APP PUBLIC .)

ADD_SUBDIRECTORY(Assets)
ADD_SUBDIRECTORY(ProtobufWrapper)
ADD_SUBDIRECTORY(DebugMessagesHandler)
