Config:
  output: ../../APP/Assets/Text
  generate_all_capital_letters: true
  generate_all_lowercase_letters: true
  generate_all_numbers: true
Fonts:
  - size: 8
    font: Minecart.ttf

TextsDefaults:
  size: 8
  font: Minecart.ttf
Texts:
  - id: percent
    text: "%"
  - id: space
    text: " "
  - id: colon
    text: ":"
  - id: degree
    text: "°"
  - id: dot
    text: "."