Config:
  output: ../../APP/Assets/Text
Defaults:
  size: 13
  font: Zachery.otf
Texts:
  - id: hour_13_57
    text: "13:57"
  - id: one
    text: "1"
  - id: two
    text: "2"
  - id: three
    text: "3"
  - id: four
    text: "4"
  - id: five
    text: "5"
  - id: six
    text: "6"
  - id: seven
    text: "7"
  - id: eight
    text: "8"
  - id: nine
    text: "9"
  - id: zero
    text: "0"
