defines:
  - STM32L452xx

includes:
  - ../../../LIB/FreeRTOS/Source/include
  - ../../../LIB/FreeRTOS/Source/portable/GCC/ARM_CM3
  - ../../../APP


steps:

  - compile FreeRTOS:
    source_directories:
      - ../../../LIB/FreeRTOS/Source
      - ../../../LIB/FreeRTOS/Source/portable/GCC/ARM_CM3

    search_subdirectories: False

    output_direcotry: ../../../Output/Obj/LIB/FreeRTOS

    types:
      - .c

  - compile FreeRTOS_heap:
    source_directories:
      - ../../../LIB/FreeRTOS/Source/portable/MemMang

    search_subdirectories: False

    output_direcotry: ../../../Output/Obj/LIB/FreeRTOS

    types:
      - _3.c