name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  x86_Clang:
    runs-on: ubuntu-latest
    container:
      image: pawelwarzecha/wooden_clock:0.1.0
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.PAT_TOKEN }}
    - name: build 
      run: mkdir -p Software/STM/build && cd Software/STM/build && cmake -DCMAKE_BUILD_TYPE=x86_Clang .. && make
    - name: test 
      run: cd Software/STM/build && cmake -DCMAKE_BUILD_TYPE=x86_GCC .. && make test
  x86_GCC:
    runs-on: ubuntu-latest
    container:
      image: pawelwarzecha/wooden_clock:0.1.0
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.PAT_TOKEN }}
    - name: build 
      run: mkdir -p Software/STM/build && cd Software/STM/build && cmake -DCMAKE_BUILD_TYPE=x86_GCC .. && make
    - name: test 
      run: cd Software/STM/build && cmake -DCMAKE_BUILD_TYPE=x86_GCC .. && make test
  ARM_Debug:
    runs-on: ubuntu-latest
    container:
      image: pawelwarzecha/wooden_clock:0.1.0
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.PAT_TOKEN }}
    - name: build 
      run: mkdir -p Software/STM/build && cd Software/STM/build && cmake -DCMAKE_BUILD_TYPE=ARM_Debug .. && make
  ARM_Release:
    runs-on: ubuntu-latest
    container:
      image: pawelwarzecha/wooden_clock:0.1.0
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.PAT_TOKEN }}
    - name: build 
      run: mkdir -p Software/STM/build && cd Software/STM/build && cmake -DCMAKE_BUILD_TYPE=ARM_Release .. && make
  ARM_Size:
    runs-on: ubuntu-latest
    container:
      image: pawelwarzecha/wooden_clock:0.1.0
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.PAT_TOKEN }}
    - name: build 
      run: mkdir -p Software/STM/build && cd Software/STM/build && cmake -DCMAKE_BUILD_TYPE=ARM_Size .. && make
  ARM_Speed:
    runs-on: ubuntu-latest
    container:
      image: pawelwarzecha/wooden_clock:0.1.0
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.PAT_TOKEN }}
    - name: build 
      run: mkdir -p Software/STM/build && cd Software/STM/build && cmake -DCMAKE_BUILD_TYPE=ARM_Speed .. && make