name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      image_version:
        description: 'Docker image version'
        required: false
        default: '0.3.0'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      image-version: ${{ steps.version.outputs.value }}
    steps:
      - id: version
        run: echo "value=${{ github.event.inputs.image_version || '0.3.0' }}" >> $GITHUB_OUTPUT

  x86_Clang:
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: pawelwarzecha/wooden_clock:${{ needs.setup.outputs.image-version }}
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.PAT_TOKEN }}
    - name: build 
      run: mkdir -p Software/STM/build && cd Software/STM/build && cmake -DCMAKE_BUILD_TYPE=x86_Clang .. && make
    - name: test 
      run: cd Software/STM/build && cmake -DCMAKE_BUILD_TYPE=x86_GCC .. && make test
  x86_GCC:
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: pawelwarzecha/wooden_clock:${{ needs.setup.outputs.image-version }}
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.PAT_TOKEN }}
    - name: build 
      run: mkdir -p Software/STM/build && cd Software/STM/build && cmake -DCMAKE_BUILD_TYPE=x86_GCC .. && make
    - name: test 
      run: cd Software/STM/build && cmake -DCMAKE_BUILD_TYPE=x86_GCC .. && make test
  ARM_Debug:
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: pawelwarzecha/wooden_clock:${{ needs.setup.outputs.image-version }}
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.PAT_TOKEN }}
    - name: build 
      run: mkdir -p Software/STM/build && cd Software/STM/build && cmake -DCMAKE_BUILD_TYPE=ARM_Debug .. && make
  ARM_Release:
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: pawelwarzecha/wooden_clock:${{ needs.setup.outputs.image-version }}
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.PAT_TOKEN }}
    - name: build 
      run: mkdir -p Software/STM/build && cd Software/STM/build && cmake -DCMAKE_BUILD_TYPE=ARM_Release .. && make
  ARM_Size:
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: pawelwarzecha/wooden_clock:${{ needs.setup.outputs.image-version }}
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.PAT_TOKEN }}
    - name: build 
      run: mkdir -p Software/STM/build && cd Software/STM/build && cmake -DCMAKE_BUILD_TYPE=ARM_Size .. && make
  ARM_Speed:
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: pawelwarzecha/wooden_clock:${{ needs.setup.outputs.image-version }}
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.PAT_TOKEN }}
    - name: build 
      run: mkdir -p Software/STM/build && cd Software/STM/build && cmake -DCMAKE_BUILD_TYPE=ARM_Speed .. && make
  Arduino:
    needs: setup
    runs-on: ubuntu-latest
    container:
      image: pawelwarzecha/wooden_clock:${{ needs.setup.outputs.image-version }}
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.PAT_TOKEN }}
    - name: Configure arduino-cli
      run: arduino-cli config add board_manager.additional_urls http://arduino.esp8266.com/stable/package_esp8266com_index.json
    - name: build 
      run: cd Software/ESP && arduino-cli compile -b esp8266:esp8266:nodemcuv2 ESP.ino
