name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_x86_Clang:
    runs-on: ubuntu-latest
    container:
      image: pawelwarzecha/wooden-clock:latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: build 
      run: ls
  build_x86_Gcc:
    runs-on: ubuntu-latest
    container:
      image: pawelwarzecha/wooden-clock:latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: build 
      run: ls

