name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_x86_Clang:
    runs-on: ubuntu-latest
    container:
      image: pawelwarzecha/wooden_clock:0.1.0
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: build 
      run: mkdir -p Software/STM/build && cd Software/STM/Build && cmake -DCMAKE_BUILD_TYPE=x86_Clang .. && make
  build_x86_Gcc:
    runs-on: ubuntu-latest
    container:
      image: pawelwarzecha/wooden_clock:0.1.0
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: build 
      run: mkdir -p Software/STM/build && cd Software/STM/Build && cmake -DCMAKE_BUILD_TYPE=x86_GCC .. && make
 

